spring:
  jackson:
  #default-property-inclusion: non_null
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.54.27.176:3306/heima_mm
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 500000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: detect
  main:
    banner-mode: console
  profiles:
    active: default
    include:
      aliyun
  redis:
    # 地址
    host: 10.54.27.176
    # 端口号
    port: 6379
    # 密码
    password: 123456
    # 超时时间，单位毫秒
    timeout: 3000
    # 数据库编号
    database: 0
    # 配置lettuce
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池中的最大空闲连接
        max-idle: 6
        # 连接池最大连接数（使用负值表示没有限制,不要配置过大，否则可能会影响redis的性能）
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）；单位毫秒
        max-wait: 1000
      #关闭超时时间；单位毫秒
      shutdown-timeout: 200

server:
  tomcat:
    uri-encoding: utf-8
  port: 9000

pagehelper:
  reasonable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.itheima.admin.pojo