aliyun:
  green:
    accessKeyId: LTAI5tPEPetpad6dHykNBX7a
    accessKeySecret: AMpUFuggculZomHiVOK9lQ7FIe8ZJK
    scenes: porn,terrorism #色情，暴力

spring:
  redis:
    # 地址
    host: 10.54.27.176
    # 端口号
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.54.27.176:3306/heima_mm
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 500000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: 9091

xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: heima-mm-task
      port: 9998