spring:
  jackson:
    #default-property-inclusion: non_null
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.54.27.176:3306/heima_mm
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 500000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: detect
  main:
    banner-mode: console
  banner:
    location: banner_dev.txt

server:
  tomcat:
    uri-encoding: utf-8
  port: 9000

pagehelper:
  reasonable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.itheima.admin.pojo

logging:
  level:
    com:
      itheima:
        admin:
          mapper: debug